### ISSUE TITLE
Wrong plugin version in the docker-compose of the release 0.2.2

### ISSUE THREAD

**Issue by jbuiquan** [green-code-initiative/ecoCode#62]
Hello,

I downloaded the latest source code release (0.2.2) as a tgz archive.
I followed the guide and started by building the plugins with `./tool_build.sh`.
Then I launched the docker-compose with `./tool_docker-init.sh`.

As we can see in the docker-compose file, we're looking for the version 0.2.3 of the plugins which don't exist because we have built the 0.2.2 versions.

```yaml
volumes:
      - type: bind
        source: ./java-plugin/target/ecocode-java-plugin-0.2.3-SNAPSHOT.jar
        target: /opt/sonarqube/extensions/plugins/ecocode-java-plugin-0.2.3-SNAPSHOT.jar
```

```bash
$ ll java-plugin/target/
total 5840
drwxr-xr-x 9 j.buiquang utilisa. du domaine    4096 févr. 28 11:03 ./
drwxrwxr-x 4 j.buiquang utilisa. du domaine    4096 févr. 28 11:03 ../
drwxr-xr-x 3 j.buiquang utilisa. du domaine    4096 févr. 28 11:03 classes/
-rw-r--r-- 1 j.buiquang utilisa. du domaine 5854022 févr. 28 11:03 ecocode-java-plugin-0.2.2.jar
# ...
```

I also found that the target are generated without the "SNAPSHOT" suffix.
